### ISSUE TITLE
please support sudo user password control

### ISSUE THREAD

**Issue by naototty** [cybozu-go/etcdpasswd#17]
like this; https://ten-snapon.com/archives/1355

**Comment by ymmt2005** [comment]
Thank you for a feature request.
Currently, etcdpasswd does not set user passwords to avoid storing sensitive data into etcd.

To clarify, users can edit `/etc/sudoers` to not ask passwords:
```
sudo ALL=(ALL) NOPASSWD: ALL
```
or ask another user's password by adding `rootpw`, `targetpw`, or `runaspw` option.

If these are not acceptable, possible options I can think are:
* Implement it as an optional feature for users who can tolerate that risk,
* Store password hashes in a secure storage such as Hashicorp Vault.

That said, the latter complicates the system and would spoil etcdpasswd's simplicity.

**Comment by ymmt2005** [comment]
Closing.
