### ISSUE TITLE
subcommand get, set and locker work fine but cert, group and user do not

### ISSUE THREAD

**Issue by reokashiwa** [cybozu-go/etcdpasswd#23]
## What

Subcommand get, set and locker work fine.
But cert, group and user do not work fine.

## How

works fine.

> % etcdpasswd set start-uid 4000
> % etcdpasswd get start-uid
> 4000
> % etcdpasswd locker add hoge
> % etcdpasswd locker list
> hoge
> % etcdpasswd locker remove reo
> %

works not fine.

> % etcdpasswd user add hoge
> 
> Error: etcdserver: key not found
> % etcdpasswd group add hoge
> 
> Error: etcdserver: key not found
> % etcdpasswd cert add hoge ~/.ssh/id_ed25519.pub
> 
> Error: not found

## Checklist

- [ ] Finish implentation of the issue
- [X] Test all functions
- [X] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@reokashiwa 
Thank you for the report.
I am afraid that you did not set `start-gid` as described in [README.md](https://github.com/cybozu-go/etcdpasswd#installation).

Anyway, the error message is not understandable and should be improved.
